const dare = [
    "Makan 2 sendok makan nasi tanpa lauk, kalau seret bisa minum.",
    "Sebut orang yang bikin kamu terdiam.",
    "Telepon gebetan sekarang dan kirim screenshot.",
    "Cuma kirim emot di setiap pesan di grup/privat selama 1 hari.",
    "Ucapkan 'Selamat datang di Who Wants To Be a Millionaire!' di semua grup yang kamu punya.",
    "Telepon mantan dan bilang kangen.",
    "Nyanyikan bagian chorus dari lagu terakhir yang kamu putar.",
    "Kirim voice note ke mantan/gebetan/pacar, bilang 'Hai (nama), mau telepon sebentar. Aku kangen banget.'",
    "Pukul meja di rumah sampai dimarahi karena berisik.",
    "Bilang ke orang random, 'Aku baru dikasih tahu kalau kita kembar pertama, terus kita pisah, lalu aku operasi plastik. Dan ini yang paling ciyusss.'",
    "Sebut nama mantan.",
    "Buat 1 pantun untuk member!",
    "Kirim daftar chat WhatsApp kamu.",
    "Chat orang random dengan bahasa gaul, lalu kirim screenshot di sini.",
    "Ceritakan hal memalukan versi kamu sendiri.",
    "Tag orang yang kamu benci.",
    "Berpura-pura kesurupan, contoh: kesurupan anjing, kesurupan belalang, kesurupan kulkas, dll.",
    "Ganti nama jadi 'I AM DONKEY' selama 24 jam.",
    "Teriak 'ma chuda ma chuda ma chuda' di depan rumahmu.",
    "Posting foto pacar/gebetan.",
    "Ceritakan tipe pacar kamu!",
    "Bilang 'aku suka sama kamu, mau jadi pacarku?' ke lawan jenis yang terakhir kamu chat (kirim di wa/tele), tunggu balasannya, kalau sudah, kirim di sini.",
    "Rekam suara kamu membaca 'titar ke age do titar, titar ke piche do titar'.",
    "Prank chat mantan dan bilang 'aku cinta kamu, tolong kembali.' tanpa bilang itu dare!",
    "Chat kontak wa sesuai urutan baterai %, lalu bilang 'aku beruntung punya kamu!'",
    "Ganti nama jadi 'I am a child of randi' selama 5 jam.",
    "Ketik dalam bahasa Bengali selama 24 jam.",
    "Gunakan foto Selmon Bhoi selama 3 hari.",
    "Kirim kutipan lagu lalu tag member yang cocok dengan kutipan itu.",
    "Kirim voice note bilang boleh aku panggil kamu baby?",
    "Screenshot panggilan WhatsApp terbaru.",
    "Bilang 'YOU ARE SO BEAUTIFUL DON'T LIE' ke cowok!",
    "Panggil member grup secara personal, dan bilang fuck you.",
    "Berpura-pura jadi ayam di depan orang tua kamu.",
    "Ambil buku random dan baca satu halaman dengan keras di voice note lalu kirim di sini.",
    "Buka pintu depan dan melolong seperti serigala selama 10 detik.",
    "Ambil selfie memalukan dan tempel di foto profil kamu.",
    "Biarkan grup memilih kata dan lagu yang terkenal. Kamu harus nyanyikan lagu itu dan kirim di voice note.",
    "Jalan dengan siku dan lutut selama kamu bisa.",
    "Nyanyikan lagu kebangsaan di voice note.",
    "Breakdance selama 30 detik di ruang tamu.",
    "Ceritakan kisah paling sedih yang kamu tahu.",
    "Buat video twerk dance dan pasang di status selama 5 menit.",
    "Makan satu potong bawang putih mentah.",
    "Tunjukkan lima orang terakhir yang kamu kirim pesan dan apa yang mereka bilang.",
    "Pasang nama lengkap kamu di status selama 5 jam.",
    "Buat video tari pendek tanpa filter hanya dengan musik dan pasang di status selama 5 jam.",
    "Telepon sahabat kamu, panggil dia bitch.",
    "Pasang foto kamu tanpa filter di status selama 10 menit.",
    "Bilang aku cinta oli london di voice note.",
    "Kirim pesan ke mantan dan bilang aku masih suka kamu.",
    "Telepon gebetan/pacar/sahabat sekarang dan screenshot di sini.",
    "Panggil salah satu member grup secara personal dan bilang kamu jelek bustard.",
    "Bilang KAMU CANTIK/TAMPAN ke salah satu orang yang ada di puncak daftar pin kamu atau orang pertama di daftar chat kamu.",
    "Kirim voice note bilang boleh aku panggil kamu baby, kalau kamu cowok tag cewek/kamu cewek tag cowok.",
    "Tulis aku cinta kamu (nama member grup random, yang online) di chat pribadi, (kalau kamu cowok tulis nama cewek/kamu cewek tulis nama cowok) ambil foto dan kirim di sini.",
    "Gunakan foto aktor Bollywood sebagai foto profil kamu selama 3 hari.",
    "Pasang foto gebetan di status dengan caption, ini gebetan saya.",
    "Ganti nama jadi 'I AM GAY' selama 5 jam.",
    "Chat salah satu kontak di WhatsApp dan bilang aku akan jadi pacar kamu selama 5 jam.",
    "Kirim voice note bilang aku suka sama kamu, mau jadi pacarku atau ga? ke orang random dari grup (kalau kamu cewek pilih cowok, kalau cowok pilih cewek).",
    "Pukul pantatmu dengan keras dan kirim suara pukulan lewat voice note.",
    "Sebutkan tipe pacar kamu dan kirim fotonya di sini dengan caption, cewek/cowok terjelek di dunia.",
    "Teriak bravoooooo dan kirim di sini lewat voice note.",
    "Ambil foto wajah kamu dan kirim di sini.",
    "Pasang foto kamu dengan caption, aku lesbian.",
    "Teriak kata-kata kasar dan kirim di sini lewat voice note.",
    "Teriak kamu bajingan di depan ibumu/papamu.",
    "Ganti nama jadi aku idiot selama 24 jam.",
    "Tampar dirimu dengan keras dan kirim suara tamparan lewat voice note.",
    "Bilang aku cinta pemilik bot xeon lewat voice note.",
    "Kirim foto pacar kamu di sini.",
    "Buat video tantangan tari TikTok dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Putuskan persahabatan dengan sahabatmu selama 5 jam tanpa memberitahu itu dare.",
    "Bilang ke salah satu temanmu kalau kamu cinta dia dan mau menikah dengannya, tanpa memberitahu itu dare.",
    "Bilang aku cinta depak kalal lewat voice note.",
    "Tulis aku lagi horny dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Tulis aku lesbian dan pasang di status, kamu bisa hapus setelah 5 jam.",
    "Cium mamamu atau papamu dan bilang aku cinta kamu.",
    "Pasang nama ayahmu di status selama 5 jam.",
    "Kirim kata-kata kasar di grup mana saja kecuali grup ini, dan kirim bukti screenshot di sini."
];

module.exports = dare