const truth = [
    "Pernah suka sama seseorang? Berapa lama?",
    "Jika kamu bisa atau jika kamu mau, di gc mana atau luar gc yang ingin kamu berteman? (mungkin beda/jenis sama)",
    "Apa ketakutan terbesar kamu?",
    "Pernah suka sama seseorang dan merasa orang itu suka juga sama kamu?",
    "Siapa nama mantan pacar teman kamu yang diam-diam kamu suka?",
    "Pernah nyolong uang dari ayah atau ibu? Alasannya?",
    "Apa yang bikin kamu bahagia saat kamu sedih?",
    "Pernah naksir satu arah? Kalau iya, siapa? Gimana rasanya bro?",
    "Pernah jadi selingkuhan orang?",
    "Hal yang paling ditakuti",
    "Siapa orang yang paling berpengaruh dalam hidup kamu?",
    "Hal apa yang membanggakan yang kamu dapat tahun ini",
    "Siapa orang yang bisa bikin kamu keren?",
    "Siapa orang yang pernah bikin kamu sangat bahagia?",
    "Siapa yang paling mendekati tipe pasangan idealmu di sini?",
    "Siapa yang kamu suka main bareng?",
    "Pernah nolak orang? Alasannya kenapa?",
    "Sebutkan kejadian yang membuat kamu sakit hati yang masih kamu ingat",
    "Prestasi apa yang kamu dapat tahun ini?",
    "Kebiasaan terburuk kamu di sekolah apa?",
    "Lagu apa yang paling sering kamu nyanyikan di kamar mandi?",
    "Pernah punya pengalaman hampir mati?",
    "Kapan terakhir kali kamu benar-benar marah? Kenapa?",
    "Siapa orang terakhir yang menelepon kamu?",
    "Kamu punya bakat tersembunyi? Apa itu?",
    "Kata apa yang paling kamu benci?",
    "Apa video YouTube terakhir yang kamu tonton?",
    "Apa yang terakhir kamu cari di Google?",
    "Siapa di grup ini yang ingin kamu tukar hidupnya selama seminggu?",
    "Apa hal paling menakutkan yang pernah terjadi padamu?",
    "Pernah kentut dan menyalahkan orang lain?",
    "Kapan terakhir kali kamu membuat orang lain menangis?",
    "Pernah menghilangkan teman?",
    "Pernah lihat mayat?",
    "Anggota keluargamu yang paling mengganggu dan kenapa?",
    "Jika kamu harus menghapus satu aplikasi dari ponsel kamu, yang mana itu?",
    "Aplikasi apa yang paling banyak menyita waktu kamu?",
    "Pernah pura-pura sakit buat pulang dari sekolah?",
    "Barang paling memalukan di kamarmu apa?",
    "Apa lima barang yang akan kamu bawa jika terjebak di pulau terpencil?",
    "Pernah tertawa sampai ngompol?",
    "Kamu mencium bau kentutmu sendiri?",
    "Pernah ngompol di kasur saat tidur?",
    "Kesalahan terbesar yang pernah kamu buat apa?",
    "Pernah nyontek saat ujian?",
    "Hal terburuk yang pernah kamu lakukan apa?",
    "Kapan terakhir kali kamu menangis?",
    "Siapa yang kamu cintai paling banyak di antara orang tuamu?",
    "Kamu kadang-kadang masukin jari ke hidung?",
    "Siapa gebetanmu waktu sekolah?",
    "Jujur aja, kamu suka sama cowok di grup ini?",
    "Pernah suka sama seseorang? Berapa lama?",
    "Kamu punya pacar?",
    "Apa ketakutan terbesar kamu?",
    "Pernah suka sama seseorang dan merasa orang itu suka juga sama kamu?",
    "Siapa nama mantan pacar teman kamu yang dulu kamu suka diam-diam?",
    "Pernah nyolong uang dari ibu atau ayah?",
    "Apa yang bikin kamu bahagia saat kamu sedih?",
    "Kamu suka seseorang yang ada di grup ini? Kalau iya, siapa?",
    "Pernah dikhianati orang?",
    "Siapa orang yang paling penting dalam hidup kamu?",
    "Hal apa yang membanggakan yang kamu dapat tahun ini?",
    "Siapa orang yang bisa bikin kamu bahagia saat kamu sedih?",
    "Siapa orang yang pernah membuatmu merasa tidak nyaman?",
    "Pernah bohong sama orang tua?",
    "Masih suka sama mantan?",
    "Siapa yang kamu suka main bareng?",
    "Pernah nyolong barang besar? Alasannya?",
    "Sebutkan kejadian yang membuat kamu sakit hati yang masih kamu ingat",
    "Prestasi apa yang kamu dapat tahun ini?",
    "Kebiasaan terburuk kamu di sekolah apa?",
    "Kamu suka pembuat bot, Luhung? 🤣",
    "Pernah berpikir balas dendam sama guru?",
    "Kamu suka perdana menteri sekarang?",
    "Kamu non-veg atau veg?",
    "Jika bisa jadi tak terlihat, apa yang pertama kali akan kamu lakukan?",
    "Rahasia apa yang kamu simpan dari orang tua?",
    "Siapa gebetan rahasiamu?",
    "Siapa orang terakhir yang kamu kepoin di media sosial?",
    "Jika jin memberi tiga permintaan, apa yang akan kamu minta?",
    "Penyesalan terbesar kamu apa?",
    "Hewan apa yang paling mirip denganmu?",
    "Berapa banyak selfie yang kamu ambil sehari?",
    "Acara masa kecil favoritmu apa?",
    "Jika bisa jadi karakter fiksi sehari, siapa yang kamu pilih?",
    "Siapa yang paling sering kamu teks?",
    "Kebohongan terbesar yang pernah kamu bilang ke orang tua apa?",
    "Siapa selebriti yang kamu suka?",
    "Mimpi paling aneh yang pernah kamu alami apa?",
    "Kamu main PUBG? Kalau iya, kirim nomor ID-mu."
];

module.exports = truth